.github/workflows/lint.yml, frontend/package.json, frontend/src/App.tsx, frontend/yarn.lock
=> Rename "rubocop" action to "lint", add FE

backend/app/bindings/api/v0/bindings/environment.rb, backend/app/controllers/api/v0/misc_controller.rb, backend/app/controllers/api/v0/misc_swagger.rb, backend/app/controllers/development/users_controller.rb, backend/spec/requests/api/v0/misc_spec.rb, docker-compose.yml, frontend/specs/homepage.test.ts, frontend/src/components/incorrect-user.tsx, frontend/src/components/index.ts, frontend/src/lib/env.ts, frontend/src/lib/user-access.tsx, frontend/src/models/environment.ts, frontend/src/models/user.ts, frontend/src/screens/dev/users.ts, frontend/src/screens/studies/index.tsx
Has a few BE changes to:
* rename env property to match the command line ENV var name
* return user info when logging in
=> redirect to proper accounts server; restrict study to researchers

frontend/specs/participant.test.ts, frontend/src/components/modal.tsx, frontend/src/main.tsx, frontend/src/screens/studies/user-listing.tsx, frontend/src/screens/study-landing.tsx
=> Open mandatory studies in iframe inside modal

frontend/specs/participant.spec.ts, frontend/specs/test.ts, frontend/src/screens/dev/index.tsx, frontend/src/screens/studies/details.tsx, frontend/src/screens/studies/edit.tsx, frontend/src/screens/studies/researcher-listing.tsx, frontend/src/screens/studies/user-listing.tsx, frontend/src/screens/study-landing.tsx
Once a study's completed it should appear disabled and not accept click events
=> Disable launching and details on completed studies

backend/app/models/research_id.rb, backend/app/models/user.rb, backend/app/services/qualtrics_launcher.rb, backend/config/environment.rb, backend/db/migrate/20210916155137_create_research_ids.rb, backend/db/schema.rb, backend/lib/unique_token.rb, backend/spec/models/research_id_spec.rb, backend/spec/services/launch_pad_spec.rb, backend/spec/services/qualtrics_launcher_spec.rb, frontend/specs/test.ts, frontend/src/screens/studies/user-listing.tsx
Adds model to store a unique random id for research participants
That id is what we will send to outside agencies so that if it's compromised, it cannot be linked back to a real OX user
=> Add ResearchId model

README.md, app.json, backend/lib/tasks/demo-users.rake, backend/lib/tasks/set_domain_config.rake
Sets up a few demo accounts for use in automated testing
=> add demo-users rake command

.github/workflows/tests.yml, backend/app/bindings/api/v0/bindings/study.rb, backend/app/controllers/api/v0/participant/studies_controller.rb, backend/app/controllers/api/v0/researcher/studies_controller.rb, backend/app/controllers/api/v0/researcher/studies_swagger.rb, backend/app/models/researcher.rb, backend/app/models/study.rb, backend/lib/patches/api/v0/bindings/study.rb, frontend/playwright.config.ts, frontend/specs/helpers.ts, frontend/specs/participant.spec.ts, frontend/specs/researcher.spec.ts, frontend/specs/test.ts, frontend/src/api/apis/StudiesApi.ts, frontend/src/api/models/Study.ts, frontend/src/components/button.tsx, frontend/src/components/icon.tsx, frontend/src/screens/studies/edit.tsx
Will allow researchers to remove a study if they make a mistake setting it up or something
=> allow deletion of  studies if they've not been used

frontend/specs/homepage.test.ts, frontend/src/components/incorrect-user.tsx
https://app.zenhub.com/workspaces/research-611c260d2f76a4001cd83a6f/issues/openstax/kenetic/65
=> log in link

Dockerfile.heroku, backend/Gemfile.lock, backend/config/environments/production.rb, backend/config/initializers/sentry.rb, backend/config/secrets.yml
needs dsn while building and also `production` environment should be symbol
=> Fix sentry logging

Dockerfile.heroku, frontend/src/components/modal.tsx, frontend/src/screens/participant-home.tsx, frontend/src/screens/researcher-home.tsx, frontend/src/screens/studies/modal.tsx, frontend/src/screens/study-details.tsx, homepage/index.html, homepage/main.js
=> set modal and iframe to be full screen

backend/Gemfile.lock, backend/app/controllers/api/v0/participant/studies_controller.rb, backend/app/controllers/api/v0/participant/studies_swagger.rb, backend/app/controllers/api/v0/swagger_responses.rb, backend/app/models/launched_study.rb, backend/app/services/launch_pad.rb, backend/db/migrate/20211129180319_aborted_launches.rb, backend/db/schema.rb, frontend/.eslintrc.js, frontend/specs/helpers.ts, frontend/src/api/apis/StudiesApi.ts, frontend/src/components/ui-states.tsx, frontend/src/lib/hooks.ts, frontend/src/models/study.ts, frontend/src/screens/study-landing.tsx
The message is shown on Qualtrics, we just redirect to studies page
=> Record when participants do not consent to a study

frontend/src/screens/studies/participant-controls.tsx
We decided it wasn't prominent enough to allow sorting by
=> remove the study:type sort control

backend/.rubocop.yml, backend/Gemfile, backend/Gemfile.lock, backend/app/controllers/api/v1/misc_swagger.rb, backend/app/controllers/api/v1/participant/studies_controller.rb, backend/app/controllers/api/v1/participant/studies_swagger.rb, backend/app/controllers/api/v1/researcher/stages_swagger.rb, backend/app/controllers/api/v1/researcher/studies_swagger.rb, backend/app/controllers/api/v1/swagger_responses.rb, backend/app/services/launch_pad.rb, backend/config/initializers/openstax_accounts.rb, backend/config/secrets.yml, backend/lib/tasks/activity_report.rake, backend/lib/tasks/demo_users.rake, backend/spec/dummy_spec.rb
also adds a accounts key/secret so it can read the usernames/emails
=> Generate a simple CSV activity report

frontend/src/models/environment.ts, homepage/index.html
- update title
- Correct accounts staging links
- Correct computed value, too
=> fix staging links

homepage/index.html
Hoping the link gets rewritten automatically when it's moved to Prod...
=> redirect to staging, not cms-staging

frontend/src/components/rewards-progress-bar.tsx, frontend/src/theme.ts
=> tweak rewards progress bar styles

backend/app/controllers/api/v1/participant/studies_controller.rb, backend/app/services/launch_pad.rb, backend/spec/requests/api/v1/participant/studies_spec.rb, frontend/specs/participant.spec.ts, frontend/src/screens/study-landing.tsx, homepage/index.html
The param name was incorrect and the landing class had some logic errors
=> Fix non consent

backend/app/controllers/api/v1/eligibility_controller.rb, backend/config/eligibility.yml, backend/spec/requests/api/v1/eligible_spec.rb
Somehow we'd missed these from the list earlier
=> add physics and polish physiology

frontend/index.html, frontend/src/favicon.svg, homepage/index.html
=> update document title and favicon

frontend/src/components/footer.tsx, frontend/src/components/modal.tsx, frontend/src/components/rewards-progress-bar.tsx, frontend/src/lib/user-access.tsx, frontend/src/screens/participant-home.tsx, frontend/src/screens/studies/participant-controls.tsx, frontend/src/screens/study-details.tsx, frontend/src/styles/main.scss
changes requested in https://docs.google.com/document/d/1whUm472f9NBYcsxhr9LkTEPcS_C0eA-ZTrM9uDkwx2s/edit#heading=h.oywc8i1hzs8a
=> make changes that came out of UI review

frontend/src/components/rewards-progress-bar.tsx
=> add the date to the progress bar goals

backend/lib/tasks/activity_report.rake
This allows us to run it on Heroku as:
`heroku run -a kinetic-web "bundle exec rake report:activity[3]" > /tmp/foo.csv`
=> write CSV to stdout

backend/app/models/study.rb, backend/app/services/launch_pad.rb, backend/lib/tasks/activity_report.rake, backend/spec/models/study_spec.rb
open is also a scope and was triggering a warning
=> Fix rake task and rename open to available?

backend/app/controllers/api/v1/participant/studies_controller.rb, backend/app/models/launched_stage.rb, backend/app/models/study.rb, backend/app/models/user.rb, backend/lib/tasks/activity_report.rake, backend/spec/models/study_spec.rb
And rename the scope to `available` as well
=> Add a few more fields to the activity report

frontend/specs/admin.spec.ts, frontend/src/screens/admin-home.tsx
The BE won't allow fetching the api endpoints but we should also hide the UI
=> redirect non-admins away from /admin

frontend/src/screens/admin/banners.tsx, frontend/src/screens/admin/rewards.tsx
Otherwise it seems like clicking the `save` button is ineffectual
=> display errors when saving fails

backend/Gemfile.lock, backend/app/services/launch_pad.rb, backend/spec/requests/api/v1/participant/studies_spec.rb, backend/spec/services/launch_pad_spec.rb, frontend/specs/admin.spec.ts, frontend/specs/helpers.ts, frontend/specs/participant.spec.ts, frontend/src/components/rewards-progress-bar.tsx, frontend/src/models/rewards.ts, frontend/src/screens/participant-home.tsx
Note this only tests against first segment, getting clarification if we should also remove "late work"
=> Only count points earned during current rewards cycle

homepage/index.html
* Removes favicon after page unloads
* Renames "Kinetic by OpenStax" to "OpenStax Kinetic"
Tagging @RoyEJohnson for review but it's a little late since we've already "deployed" it on the CMS 😭
=> update homepage 

frontend/src/components/banners-bar.tsx, frontend/src/components/footer.tsx, frontend/src/components/menu.tsx, frontend/src/components/top-navbar.tsx, frontend/src/models/environment.ts
=> top align banner close button, adjust padding and alignment for top nav

frontend/src/screens/learner.tsx
resolves https://github.com/openstax/research/issues/163
We now exclude completed & mandatory studies, then 3 random ones.
Sort completed at bottom and show different no studies message
=> rename popular to highlighted, pick random studies

frontend/src/components/multi-session-bar.tsx, frontend/src/components/segment-bar.tsx, frontend/src/models/study.ts, frontend/src/screens/learner/details.tsx
Will hopefully be more clear that they need to wait for second stage to open
also makes stage font a bit smaller and leaves continue button on screen but disables it
=> add a clock icon to middle of multi session bar 

frontend/src/components/footer.tsx
=> vertically center logos

frontend/src/components/banners-bar.tsx, frontend/src/components/top-navbar.tsx, frontend/src/theme.ts
Changes
- "X" button in top right corner
- No margins and smaller font on mobile view
- Center aligned all nav items
- Changed background color of banner
- Centered banner text
- Padding between banner text/close button
=> 195 reward banner css

frontend/src/screens/learner/card.tsx
this keeps the title's aligned
resolves https://github.com/openstax/research/issues/201
=> force space allocation for tags

frontend/specs/helpers.ts, frontend/specs/learner.spec.ts, frontend/specs/test.ts, frontend/src/screens/learner.tsx, frontend/src/screens/learner/studies.ts
Sorts studies randomly and remembers order in localStorage for 30 days or until new studies appear
Fixes https://github.com/openstax/research/issues/203
=> keep study order the same across reloads

frontend/src/components/footer.tsx, frontend/src/components/form.tsx, frontend/src/components/resource-links.tsx, frontend/src/screens/account-details.tsx
resolves openstax/research#197
=> Styling updates, consisten footer section text sizing

frontend/src/components/footer.tsx, homepage/index.html
=> Fix homepage mobile supporter section, align with styles on LD

frontend/package.json, frontend/src/components/multi-session-bar.tsx, frontend/src/components/rewards-progress-bar.tsx, frontend/src/components/segment-bar.tsx, frontend/src/components/top-navbar.tsx, frontend/src/screens/learner/card.tsx, frontend/src/screens/learner/details.tsx, frontend/src/screens/learner/studies.ts, frontend/src/screens/study-landing.tsx, frontend/yarn.lock
This allows the height to be set based on needed label height, whereas absolute positioning would overflow if longer than 2 lines
fixes https://github.com/openstax/research/issues/202
=> Use flex box to layout segments

frontend/src/components/rewards-progress-bar.tsx, frontend/src/screens/learner/studies.ts
picks the first 3 eligible studies to highlight so the selection will be retained across reloads
=> pick the same 3 highlighted studies

backend/app/controllers/application_controller.rb, backend/app/controllers/static_controller.rb, backend/config/environment.rb, backend/lib/cookie_authentication.rb
Somehow google started listing the app homepage vs the openstax.org/kinetic page
A future update may add a proper robots.txt but this will at least ensure users get to the correct page and hopefully influence Google toward listing the correct page
=> redirect to hompage if not logged in

frontend/src/components/off-canvas.tsx
resolves openstax/research#220
=> Hide offcanvas on navigate

homepage/index.html
=> Remove padding on header

frontend/src/screens/learner/card.tsx, frontend/src/screens/learner/details.tsx
=> add hardcoded multi session studies until #204 is complete

backend/app/bindings/api/v1/bindings/participant_study.rb, backend/app/controllers/api/v1/participant/studies_open_api.rb, backend/app/models/study.rb, backend/config/secrets.yml, backend/lib/patches/api/v1/bindings/participant_study.rb, frontend/src/api/models/ParticipantStudy.ts, frontend/src/screens/learner/studies.ts
Adds a configuration to list qualtric study ids to feature.  In the future we can populate the setting from an admin panel
=> feature specific studies

homepage/index.html
closes
openstax/research#296
openstax/research#297
=> Left align text in funder section

frontend/src/components/resource-links.tsx, homepage/index.html
=> Update FAQ links to spec

frontend/src/components/resource-links.tsx, frontend/src/screens/account-details.tsx, frontend/src/screens/researcher-home.tsx
=> Update account details page

backend/README.md
=> Update backend README.md

backend/Gemfile.lock
#241 removed image_processing but I forgot to run `bundle install` afterwards
=> image_processing was removed but forgot to bundle

backend/app/services/clone_survey.rb, backend/app/services/qualtrics_api.rb, backend/app/services/qualtrics_test_data.rb, backend/config/secrets.yml, backend/spec/services/qualtrics_test_data_spec.rb
Only used for testing so far, but will be of use in the future
=> code to clone Qualtrics survey

frontend/src/common.ts, frontend/src/components/file-upload.tsx, frontend/src/components/form-select.ts, frontend/src/components/form/character-count.tsx, frontend/src/components/form/field-error-message.tsx, frontend/src/components/icon.tsx, frontend/src/components/index.ts, frontend/src/screens/admin/banners.tsx, frontend/src/screens/admin/rewards.tsx, frontend/src/screens/analysis/edit.tsx, frontend/src/screens/learner/card.tsx, frontend/src/screens/researcher/account/researcher-account-form.tsx, frontend/src/screens/researcher/account/researcher-account-page.tsx, frontend/src/screens/researcher/studies/create/action-footer.tsx, frontend/src/screens/researcher/studies/create/edit-study.tsx, frontend/src/screens/researcher/studies/create/forms/additional-sessions.tsx, frontend/src/screens/researcher/studies/create/forms/finalize-study.tsx, frontend/src/screens/researcher/studies/create/forms/form-components.tsx, frontend/src/screens/researcher/studies/create/forms/internal-details.tsx, frontend/src/screens/researcher/studies/create/forms/participant-view.tsx, frontend/src/screens/researcher/studies/create/forms/research-team.tsx, frontend/src/screens/researcher/studies/create/forms/review-study.tsx, frontend/src/screens/researcher/studies/create/image-library.tsx, frontend/src/screens/researcher/studies/create/researcher-study-landing.tsx, frontend/src/screens/researcher/studies/dashboard/studies-table.tsx, frontend/src/screens/researcher/studies/dashboard/study-action-notification.tsx, frontend/src/screens/researcher/studies/dashboard/study-actions.tsx
Sundry now splits it's exports so that the workspaces editor can import only the bare minimum and can SSR render it's forms
=> Update sundry to latest

frontend/package.json, frontend/specs/admin.spec.ts, frontend/specs/learner.spec.ts, frontend/specs/test.ts, frontend/src/components/alert.tsx, frontend/src/components/incorrect-user.tsx, frontend/src/components/segment-bar.tsx, frontend/src/screens/admin/banners.tsx, frontend/src/screens/admin/rewards.tsx, frontend/src/screens/learner.tsx, frontend/src/screens/learner/details.tsx, frontend/src/screens/researcher/account/researcher-account-form.tsx, frontend/src/screens/researcher/account/researcher-account-page.tsx, frontend/src/screens/researcher/studies/create/image-library.tsx, frontend/src/screens/researcher/studies/dashboard/researcher-studies.tsx, frontend/src/screens/researcher/studies/dashboard/studies-table.tsx, frontend/src/screens/study-landing.tsx, frontend/yarn.lock
"data-testid" is what the playwright and testing-library docs recommend, it seems to be the "standard" way to locate elements of interest while running test harnesses.
I updated sundry to use it on elements, which means consumers will also need updated as well
=> update sundry; rename data-test-id to data-testid

backend/app/models/analysis.rb, backend/app/models/analysis_response_export.rb, backend/app/services/qualtrics_test_data.rb
Calling attach clears previous files, need to call it only once with the attributes
=> fix broken response generation

frontend/package.json, frontend/src/components/form-select.ts, frontend/yarn.lock
Update sundry with new config method
=> Update sd inputs

frontend/src/screens/learner/details.tsx
[Study Card - About Researcher #484](https://app.zenhub.com/workspaces/kinetic-611c260d2f76a4001cd83a6f/issues/gh/openstax/research/484)
=> add separation between researcher-bio + logic for lead = pi

frontend/src/screens/learner/card.tsx
=> Add new study label

backend/app/services/qualtrics_api.rb
I added this to clean out all the testing surveys that we'd created while testing.
=> add methods to remove qualtrics surveys

frontend/index.html
Per https://github.com/openstax/rex-web/pull/2026 we need to use a script tag vs loading it as part of our bundle
=> Add Osano via their "direct install" method

frontend/specs/helpers.ts, frontend/src/screens/researcher/studies/overview/edit-submitted-study.tsx, frontend/src/screens/researcher/studies/overview/finalize-study.tsx
https://app.zenhub.com/workspaces/kinetic-611c260d2f76a4001cd83a6f/issues/gh/openstax/research/478
=> Only show finalize study section when user checks qualtrics

frontend/src/components/navbar/top-navbar.tsx, frontend/src/screens/researcher/studies/overview/study-overview.tsx
[Relevant ticket here](https://app.zenhub.com/workspaces/kinetic-611c260d2f76a4001cd83a6f/issues/gh/openstax/research/519)
=> Hide analysis entrypoints

frontend/package.json, frontend/src/components/navbar/top-navbar.tsx, frontend/src/models/study.ts, frontend/src/screens/admin/approve-studies.tsx, frontend/src/screens/researcher/studies/create/forms/additional-sessions.tsx, frontend/src/screens/researcher/studies/dashboard/researcher-studies.tsx, frontend/src/screens/researcher/studies/dashboard/studies-table.tsx, frontend/src/screens/researcher/studies/dashboard/study-actions.tsx, frontend/src/screens/researcher/studies/overview/edit-submitted-study.tsx, frontend/src/theme.ts, frontend/yarn.lock
[Ticket](https://app.zenhub.com/workspaces/kinetic-611c260d2f76a4001cd83a6f/issues/gh/openstax/research/489)
=> UI tweaks and fixes per viki feedback

frontend/src/components/manage-cookies.tsx, frontend/src/components/resource-links.tsx
=> remove cookie icon and add "Manage Cookies" link to footer

backend/app/models/study.rb, backend/spec/models/study_spec.rb
Doing so clears the config and qualtrics stopped working
=> do not re-create stages unless needed

backend/app/models/study.rb, backend/spec/models/study_spec.rb, backend/spec/requests/api/v1/participant/studies_spec.rb, frontend/specs/data-helpers.ts, frontend/specs/helpers.ts, frontend/specs/learner.spec.ts, frontend/specs/researcher/analysis-helper.ts, frontend/specs/researcher/analysis.spec.ts
Sabitha marked her study as paused but it was still showing up for participants
=> Only studies that have an active stage are available

backend/spec/requests/api/v1/participant/studies_spec.rb, frontend/specs/helpers.ts, frontend/specs/researcher-account.spec.ts, frontend/specs/researcher/analysis-helper.ts, frontend/src/screens/study-landing.tsx
Also removed the timeouts from the test as they seemed to be irrelevant
=> Check if user completed demographic survey

backend/app/services/learner_activity_report.rb, backend/spec/tasks/activity_report_spec.rb
https://kineticopenstax.atlassian.net/browse/ENG-48
=> Dont include non-consented responses or emails

backend/app/controllers/api/v1/researcher/responses_controller.rb, backend/config/initializers/cors.rb, backend/config/routes.rb, backend/spec/requests/api/v1/researcher/responses_spec.rb
Use id with cookie auth for them vs api key and need CORS enabled for blob downloads
=> Fix downloading info

frontend/src/components/icon.tsx, frontend/src/screens/learner.tsx, frontend/src/screens/learner/studies.ts
Added the feature based on the following [ticket](https://openstax.atlassian.net/browse/RENG-104?atlOrigin=eyJpIjoiNGNjZWU3ZmFjMzk4NDc4ZjkzMTdiZGQyNzRjYmYxZGEiLCJwIjoiaiJ9)
[Design Spec](https://www.figma.com/design/MVxS1h1qovYyDqbWf3DTyF/Version-3.0-Apr24?node-id=1458-2632&t=hvSypsZ5u0YtLk6G-0)
The learner can now sort based on the duration of the study. (5 min or 15min or 25min).
=> Added a feature to sort studies based on duration

frontend/src/components/footer.tsx, frontend/src/screens/learner.tsx, frontend/src/screens/learner/card.tsx
- Reduced the openning delay of study preview from 2000ms to 500ms
- Changed the color of the footer and gutter
=> Minor changes

backend/app/services/open_badge_api.rb
Fixed the pdf bug, which was caused due to the + signs in the user emails
=> Fix pdf download bug

backend/app/controllers/api/v1/admin/reports_controller.rb, backend/app/mailers/user_mailer.rb, backend/app/services/learner_activity_report.rb, frontend/src/screens/admin/admin-reports.tsx
Removed the column stage points and added the columns study path title and completed study path, to the reports csv file
Also removed the feature of downloading reports and added the feature to email the reports to the admin, sent a notification when the email is sent successfully.
=> Modifed Admin Reports

backend/app/bindings/api/v1/bindings/user_preferences.rb, backend/app/controllers/api/v1/preferences_open_api.rb, backend/db/migrate/20241219132405_update_user_preferences.rb, backend/db/structure.sql, backend/spec/requests/api/v1/preferences_spec.rb, frontend/src/api/models/UserPreferences.ts, frontend/src/screens/account-details.tsx
Removed prize cycle deadlines and new prize cycle preferences, and added a new preference digital badge available email.
Updated the migrations, bindings and tests respectively.
=> Modified user preferences
