- Dockerfile.heroku
- app.json
- backend/Gemfile
- backend/Gemfile.lock
- backend/config/environments/production.rb
- backend/config/secrets.yml
- backend/lib/tasks/review_app_predestroy.rake
- backend/lib/tasks/review_app_setup.rake
Using a new robot user (heroku-labs) that can only assume one role (research-labs-dns) that can only do a limited sot of operations on the labs[.sandbox].openstax.org hosted zones. This allows automated creation of deployments for every PR, under an openstax.org domain, so all the cookie work!
> Implement Heroku review apps w/ custom openstax domain

- frontend/src/screens/studies/edit.tsx
That's what researchers will need to use when adding the return step
> display return url when editing a study

- backend/app/models/stage.rb
- backend/app/services/qualtrics_launcher.rb
- backend/spec/models/admin_spec.rb
- backend/spec/models/launched_stage_spec.rb
- backend/spec/models/launched_study_spec.rb
- backend/spec/models/researcher_spec.rb
- backend/spec/models/study_researcher_spec.rb
- backend/spec/services/qualtrics_launcher_spec.rb
By passing the  study id to qualtrics, surveys can set the return url to be:
`https://kenetic.openstax.org/study/land/${e://Field/study_id}` or `https://staging.kenetic.openstax.org/study/land/${e://Field/study_id}` for testing
When setting up the study, two pieces of embedded data must be specified, the `research_id` and `study_id`
> Send study id to qualtrics

- backend/app/services/qualtrics_launcher.rb
The params were being encoded, hash taken, then encoded again
That caused urls to have their `/` characters doubly encoded
> do not double url encode values

- backend/Gemfile
- backend/Gemfile.lock
- backend/config/initializers/doorkeeper.rb
accounts-rails needs it to be present even if it's not used, and then in turn it needs openstax_api
> Add a minimal Doorkeeper config

- backend/app/controllers/api/v1/participant/studies_controller.rb
- backend/spec/requests/api/v1/participant/studies_spec.rb
we shouldn't mark the study as complete when it's aborted.  this allows a user to resume it later if they choose to
> don't mark aborted studies as completed

- backend/config/initializers/cors.rb
The earlier #108 didn't work, and reading https://github.com/cyu/rack-cors carefully there's no mention of using wildcards with strings on origin checks, it suggests regex
> use regex for rack:ors

- backend/app/controllers/api/v1/participant/studies_controller.rb
- frontend/src/screens/study-details.tsx
If the button was double clicked the launches could occur concurrently and cause a:
> PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_launched_studies_on_user_id_and_study_id"
DETAIL:  Key (user_id, study_id)=(a05196be-0400-4ff3-a0ec-912ce1f568d5, 2) already exists.
https://sentry.io/organizations/openstax/issues/2967634068/?environment=production&project=6051748
> prevent duplicate launches

- backend/config/initializers/sentry.rb
- backend/config/secrets.yml
It's called from REX which has huge traffic and exhausted our monthly transactions limit.
> Limit sampling to the api eligibility endpoint

- frontend/specs/participant.spec.ts
- frontend/src/screens/study-landing.tsx
This allows qualtrics study to continue with the behavior of passing consent=false and studies not being marked as completed
> default abort flag to inverse of consent

- .github/workflows/lint.yml
- .github/workflows/tests.yml
GitHub is removing its 18.04 runners
> update lts to 22.04

- frontend/src/components/packaged-icons.ts
- frontend/src/screens/learner/details.tsx
This is how the figma did it, which meant there wasn't an straight SVG to download.  this seems to work well though
fixes https://github.com/openstax/research/issues/205
> construct "personality" icon using '#' char overlay

- frontend/src/components/rewards-progress-bar.tsx
resolves overflow in https://github.com/openstax/research/issues/202
> fix rewards bar overflow on mobile

- frontend/src/components/footer.tsx
- frontend/src/components/ox-colored-stripe.tsx
- frontend/src/components/styled-buttons.tsx
- frontend/src/screens/learner/card.tsx
- frontend/src/screens/learner/details.tsx
- frontend/src/styles/bootstrap.scss
- frontend/src/theme.ts
Viki updated some [specs around color](https://docs.google.com/document/d/1Rw5y4xlylS2wcu0qUljJHV1RMXulUxYYGUNJyt94iLY/edit#heading=h.d9qgt6saek69)
Default text on the site is updated and made a lot of inline `css` redundant
> Cleanup theme colors and organize naming per specs

- frontend/specs/researcher.spec.ts
this kept silently timing out in the tests
the `.modal-header` selector never matches because the modal is already gone at this point
> playwright test selector bug

- frontend/src/screens/studies/modal.tsx
Something seems to have changed and qualtrics content inside the iframe no longer has a height attached to it, causing the iframe to no longer expand
> set a min-height for modal content

- backend/config/environments/production.rb
It seems like occasionally cloudfront will set the HTTP_X_FORWARDED_FOR to multiple IPs and trigger that check to fail.  symptoms are a ActionDispatch::RemoteIp::IpSpoofAttackError being raised resulting in a 500 error
> turn off ip spoofing checks

- backend/app/services/open_badge_api.rb
- backend/app/services/user_info.rb
Added the authorization token to the http request and changed it from form to json as per the API documentation. @chrisbendel you were right, the email_address is handled differently in production and development. I have also modified the development userInfo object to match the production one
> Fixed the obf email issue

- frontend/src/components/footer.tsx
- frontend/src/screens/achievements.tsx
- frontend/src/screens/learner.tsx
- frontend/src/screens/learner/card.tsx
- frontend/src/screens/studyBanner.tsx
- Improved the responsiveness of study cards and studies page
- Made the study banner and currated studies responsive
- Improved the responsiveness of Achievements page
- Added a loading overlay
> Improved mobile and tablet exp

- backend/Gemfile
- backend/Gemfile.lock
- backend/app/services/open_badge_api.rb
- backend/config/initializers/schedule.rb
- This PR sets up a cron job, to fetch the badges every 24h. The task is also run immediately after the application starts up.
- Utilized rufus-scheduler to setup the cron job.
- The badge ids are fetched first, followed by badge info.
> Improving application performance

- backend/app/services/learner_activity_report.rb
Requested by researchers so they can easily match OpenStax users to activity in Qualtrics
> add user uuid to activity report
